variables:
  task_id:  
    description: 'argonaut unique build run id'
    required: true
  task_name:
    description: 'task name'
    required: false
  ref:
    description: 'branch, tag, sha ref to perform build on'
    required: true
  arg_auth_token:  
    description: 'temporary organization auth token for argonaut'
    required: true
  extra_args:
    description: 'extra field that can used for future purpose, format : key1=value1,key2=value2,...'
    required: false

stages:
  - dagger

dagger-execute:
  stage: dagger
  image:
    name: golang:alpine
  services:
    - docker:dind
  script:
    - ls -lrt
    - pwd
    - user_repo_dir_root=$(pwd)
    - cd ..
    - git clone git@github.com:argonautdev/argonaut-action.git
    - cd argonaut-action/ci/
    - ARG_AUTH_TOKEN="${{ inputs.arg-auth-token }}" go run *.go ${{ inputs.task-id }} ${user_repo_dir_root}
