variables:
  task_id:  
    description: 'argonaut unique build run id'
  task_name:
    description: 'task name'
  ref:
    description: 'branch, tag, sha ref to perform build on'
  auth_key:  
    description: 'argonaut auth key/clientId'
  auth_secret:  
    description: 'argonaut auth pass/secret'
  extra_args:
    description: 'extra field that can used for future purpose, format : key1=value1,key2=value2,...'

stages:
  - dagger

dagger-execute:
  stage: dagger
  image:
    name: golang:alpine
  services:
    - docker:dind
  variables: 
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - apk update
    - apk add git
    - apk add docker-cli
  script:
    - user_repo_dir=$(pwd)
    - GIT_SHORT_SHA=$(git rev-parse --short HEAD)
    - pwd
    - cd ..
    - mkdir -m 777 argonaut-action
    - git clone -b main https://github.com/argonautdev/argonaut-action.git
    - cd argonaut-action/ci/
    - ARG_AUTH_KEY="$auth_key" ARG_AUTH_SECRET="$auth_secret" SHORT_SHA="${GIT_SHORT_SHA}" go run *.go $task_id ${user_repo_dir}