name: 'argonaut-action'
description: 'argonaut action for running ci task'
inputs:
  task-id:  
    description: 'argonaut unique build run id'
    required: true
  task-name:
    description: 'task name'
    required: false
  ref:
    description: 'branch, tag, sha ref to perform build on'
    required: true
  arg-auth-token:  
    description: 'temporary organization auth token for argonaut'
    required: true
  extra-args:
    description: 'extra field that can used for future purpose, format : key1=value1,key2=value2,...'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: user-repo
        ref: ${{ inputs.ref }}
        submodules: 'recursive'
    - name: Fetch repo
      uses: actions/checkout@v3
      with:
        path: argonaut-action
        ref: main
        repository: argonautdev/argonaut-action
        submodules: 'recursive'
    - name: Run Dagger pipeline
      run: |
        user_repo_dir_root=$(pwd)
        cd argonaut-action/ci/
        ARG_AUTH_TOKEN="${{ inputs.arg-auth-token }}" go run *.go ${{ inputs.task-id }} ${user_repo_dir_root}/user-repo
      shell: bash

