name: 'argonaut-action'
description: 'argoanut action for running build process'
inputs:
  build-run-id:  
    description: 'argonaut unique build run id'
    required: true
  ref:
    description: 'branch, tag, sha ref to perform build on'
    required: false
  arg-key:  
    description: 'argonaut organization key'
    required: true
  arg-secret:  
    description: 'argonaut organization secret'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: user-repo
        ref: ${{ inputs.ref }}
    - name: Fetch repo
      uses: actions/checkout@v3
      with:
        path: argoanut-action
        ref: main
        repository: argonautdev/argonaut-action
        submodules: 'recursive'
    - name: Run Dagger pipeline
      run: |
        pwd
        ls -lrt
        ARG_KEY=${{ inputs.arg-key }} ARG_SECRET=${{ inputs.arg-secret }} go run argonaut-action/ci/main.go test /user-repo
      shell: bash

