name: 'argonaut-action'
description: 'argonaut action for running ci task'
inputs:
  task-id:  
    description: 'argonaut unique build run id'
    required: true
  task-name:
    description: 'task name'
    required: false
  ref:
    description: 'branch, tag, sha ref to perform build on'
    required: true
  auth-key:  
    description: 'argonaut auth key/clientId'
    required: true
  auth-secret:  
    description: 'argonaut auth pass/secret'
    required: true
  extra-args:
    description: 'extra field that can used for future purpose, format : key1=value1,key2=value2,...'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - run: echo ::set-output name=user_repo_name::${GITHUB_REPOSITORY#*/}
      id: user_repo_vars
      shell: bash
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ steps.user_repo_vars.outputs.user_repo_name }}
        ref: ${{ inputs.ref }}
        submodules: 'recursive'
    - name: Fetch repo
      uses: actions/checkout@v3
      with:
        path: argonaut-action
        ref: main
        repository: argonautdev/argonaut-action
        submodules: 'recursive'
    - name: Run Dagger pipeline
      run: |
        ls -lrt
        cd ${GITHUB_REPOSITORY#*/}
        user_repo_dir=$(pwd)
        GIT_SHORT_SHA=$(git rev-parse --short HEAD)
        cd -
        cd argonaut-action/ci/
        ARG_AUTH_KEY="${{ inputs.auth-key }}" ARG_AUTH_SECRET="${{inputs.auth-secret}}" SHORT_SHA="${GIT_SHORT_SHA}" go run *.go ${{ inputs.task-id }} ${user_repo_dir}
      shell: bash

